export type ElectronicsType = "microcontroller" | "sbc" | "soc";

export interface CommandElectronicsSpec {
  id: string;
  brand: string;
  model: string;
  type: ElectronicsType;
  cpu: string;
  flashKb?: number;
  ramKb?: number;
  gpio: number;
  interfaces: string[];
  voltageV: number;
  currentMa: { idle: number; active: number };
  weightG: number;
  dimensionsMm: { l: number; w: number; h: number };
  notes?: string;
}

export const COMMAND_ELECTRONICS_CATALOG: CommandElectronicsSpec[] = [
  // ── Arduino ─────────────────────────────────────────────────────────────────
  {
    id: "arduino-uno-r3",
    brand: "Arduino",
    model: "Uno R3",
    type: "microcontroller",
    cpu: "ATmega328P @ 16 MHz",
    flashKb: 32,
    ramKb: 2,
    gpio: 20,
    interfaces: ["UART", "I2C", "SPI", "USB"],
    voltageV: 5.0,
    currentMa: { idle: 46, active: 200 },
    weightG: 25,
    dimensionsMm: { l: 68, w: 53, h: 14 },
    notes: "Carte de référence Arduino. UART pour connexion SSC-32U ou Maestro.",
  },
  {
    id: "arduino-mega-2560",
    brand: "Arduino",
    model: "Mega 2560",
    type: "microcontroller",
    cpu: "ATmega2560 @ 16 MHz",
    flashKb: 256,
    ramKb: 8,
    gpio: 54,
    interfaces: ["UART ×4", "I2C", "SPI", "USB"],
    voltageV: 5.0,
    currentMa: { idle: 93, active: 500 },
    weightG: 37,
    dimensionsMm: { l: 101, w: 53, h: 14 },
    notes: "54 GPIO, 4 UART. Idéal pour piloter plusieurs contrôleurs SSC-32U en parallèle.",
  },
  {
    id: "arduino-nano",
    brand: "Arduino",
    model: "Nano",
    type: "microcontroller",
    cpu: "ATmega328P @ 16 MHz",
    flashKb: 32,
    ramKb: 2,
    gpio: 22,
    interfaces: ["UART", "I2C", "SPI", "USB Mini-B"],
    voltageV: 5.0,
    currentMa: { idle: 19, active: 200 },
    weightG: 7,
    dimensionsMm: { l: 45, w: 18, h: 12 },
    notes: "Format mini breadboard. Même CPU que l'Uno.",
  },
  {
    id: "arduino-nano-33-ble",
    brand: "Arduino",
    model: "Nano 33 BLE Sense",
    type: "microcontroller",
    cpu: "nRF52840 @ 64 MHz",
    flashKb: 1024,
    ramKb: 256,
    gpio: 22,
    interfaces: ["UART", "I2C", "SPI", "USB", "BLE 5.0"],
    voltageV: 3.3,
    currentMa: { idle: 8, active: 150 },
    weightG: 5,
    dimensionsMm: { l: 45, w: 18, h: 10 },
    notes: "BLE 5.0 intégré, IMU 9 axes. 3,3V logique.",
  },
  // ── ESP ──────────────────────────────────────────────────────────────────────
  {
    id: "esp32-devkit-v1",
    brand: "Espressif",
    model: "ESP32 DevKit V1",
    type: "microcontroller",
    cpu: "ESP32 dual-core Xtensa LX6 @ 240 MHz",
    flashKb: 4096,
    ramKb: 520,
    gpio: 34,
    interfaces: ["WiFi 802.11n", "BLE 4.2", "UART ×3", "I2C ×2", "SPI ×4", "USB"],
    voltageV: 3.3,
    currentMa: { idle: 20, active: 240 },
    weightG: 10,
    dimensionsMm: { l: 51, w: 28, h: 11 },
    notes: "WiFi + BLE intégrés. Très populaire pour robots sans-fil. 3,3V logique.",
  },
  {
    id: "esp32-s3-devkit",
    brand: "Espressif",
    model: "ESP32-S3 DevKit",
    type: "microcontroller",
    cpu: "ESP32-S3 dual-core Xtensa LX7 @ 240 MHz",
    flashKb: 8192,
    ramKb: 512,
    gpio: 45,
    interfaces: ["WiFi 802.11n", "BLE 5.0", "UART ×3", "I2C ×2", "SPI ×4", "USB-OTG"],
    voltageV: 3.3,
    currentMa: { idle: 20, active: 350 },
    weightG: 12,
    dimensionsMm: { l: 68, w: 28, h: 12 },
    notes: "S3 : USB natif, plus de GPIO, AI accéléré.",
  },
  {
    id: "esp8266-nodemcu",
    brand: "Espressif",
    model: "ESP8266 NodeMCU v3",
    type: "microcontroller",
    cpu: "Tensilica L106 @ 80 MHz",
    flashKb: 4096,
    ramKb: 80,
    gpio: 11,
    interfaces: ["WiFi 802.11b/g/n", "UART", "I2C", "SPI", "USB"],
    voltageV: 3.3,
    currentMa: { idle: 15, active: 170 },
    weightG: 7,
    dimensionsMm: { l: 58, w: 31, h: 10 },
    notes: "WiFi uniquement. GPIO limités — convient pour commande simple.",
  },
  // ── Raspberry Pi ──────────────────────────────────────────────────────────────
  {
    id: "raspberry-pi-zero-2w",
    brand: "Raspberry Pi",
    model: "Pi Zero 2 W",
    type: "sbc",
    cpu: "ARM Cortex-A53 quad-core @ 1 GHz",
    ramKb: 512 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11n", "BLE 4.2", "UART", "I2C", "SPI", "USB Micro"],
    voltageV: 5.0,
    currentMa: { idle: 100, active: 350 },
    weightG: 10,
    dimensionsMm: { l: 65, w: 30, h: 5 },
    notes: "SBC compact. Linux complet, Python/ROS. Idéal embarqué si poids critique.",
  },
  {
    id: "raspberry-pi-3b-plus",
    brand: "Raspberry Pi",
    model: "Pi 3 B+",
    type: "sbc",
    cpu: "ARM Cortex-A53 quad-core @ 1,4 GHz",
    ramKb: 1024 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11ac", "BLE 4.2", "Ethernet", "UART", "I2C", "SPI", "USB ×4"],
    voltageV: 5.0,
    currentMa: { idle: 400, active: 1200 },
    weightG: 45,
    dimensionsMm: { l: 85, w: 56, h: 17 },
    notes: "SBC complet. Bon choix si puissance de calcul nécessaire (vision, IA embarquée).",
  },
  {
    id: "raspberry-pi-4b-2g",
    brand: "Raspberry Pi",
    model: "Pi 4 B (2 Go)",
    type: "sbc",
    cpu: "ARM Cortex-A72 quad-core @ 1,8 GHz",
    ramKb: 2048 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11ac", "BLE 5.0", "Ethernet Gbit", "UART", "I2C", "SPI", "USB 3.0 ×2", "USB 2.0 ×2"],
    voltageV: 5.0,
    currentMa: { idle: 600, active: 3000 },
    weightG: 46,
    dimensionsMm: { l: 85, w: 56, h: 17 },
    notes: "SBC haute performance. Consommation élevée — batterie LiPo nécessaire.",
  },
  // ── Teensy ────────────────────────────────────────────────────────────────────
  {
    id: "teensy-40",
    brand: "PJRC",
    model: "Teensy 4.0",
    type: "microcontroller",
    cpu: "ARM Cortex-M7 @ 600 MHz",
    flashKb: 1984,
    ramKb: 1024,
    gpio: 40,
    interfaces: ["UART ×8", "I2C ×3", "SPI ×3", "USB", "CAN"],
    voltageV: 3.3,
    currentMa: { idle: 10, active: 100 },
    weightG: 7,
    dimensionsMm: { l: 35, w: 18, h: 5 },
    notes: "MCU très rapide. Excellent pour calcul cinématique temps réel (Hexapod).",
  },
  {
    id: "teensy-41",
    brand: "PJRC",
    model: "Teensy 4.1",
    type: "microcontroller",
    cpu: "ARM Cortex-M7 @ 600 MHz",
    flashKb: 7936,
    ramKb: 1024,
    gpio: 55,
    interfaces: ["UART ×8", "I2C ×3", "SPI ×3", "USB", "CAN ×2", "Ethernet"],
    voltageV: 3.3,
    currentMa: { idle: 10, active: 120 },
    weightG: 9,
    dimensionsMm: { l: 61, w: 18, h: 5 },
    notes: "Version étendue du 4.0 avec Ethernet et plus de GPIO.",
  },
  // ── STM32 ─────────────────────────────────────────────────────────────────────
  {
    id: "stm32-nucleo-f446re",
    brand: "STMicroelectronics",
    model: "Nucleo-F446RE",
    type: "microcontroller",
    cpu: "ARM Cortex-M4 @ 180 MHz",
    flashKb: 512,
    ramKb: 128,
    gpio: 76,
    interfaces: ["UART ×6", "I2C ×3", "SPI ×4", "USB", "CAN"],
    voltageV: 3.3,
    currentMa: { idle: 15, active: 300 },
    weightG: 28,
    dimensionsMm: { l: 69, w: 51, h: 14 },
    notes: "MCU STM32 haute perf. Compatible Arduino Uno shield via connecteur.",
  },
];

export function findCommandElectronics(id: string): CommandElectronicsSpec | undefined {
  return COMMAND_ELECTRONICS_CATALOG.find((c) => c.id === id);
}
