// Snapshot des catalogues matériels intégrés (référentiels). Source de vérité
// initiale, recopiée depuis src/model/{servoTypes,servoControllers,
// commandElectronics,peripherals}.ts. Le serveur n'importe pas le code client ;
// ce fichier est donc une copie autonome utilisée pour seeder la table
// `catalog_entries` au démarrage (idempotent — voir db.ts).
//
// ⚠️ Garder en cohérence avec les types client. Les entrées sont stockées telles
// quelles (JSON) ; le client les valide à nouveau via Zod.

export type CatalogKind =
  | "servoType"
  | "servoController"
  | "commandElectronics"
  | "peripheral";

export const CATALOG_KINDS: CatalogKind[] = [
  "servoType",
  "servoController",
  "commandElectronics",
  "peripheral",
];

// ── Servomoteurs ───────────────────────────────────────────────────────────────
const SERVO_TYPES_SEED = [
  {
    id: "rs-475hb",
    brand: "Renegade",
    model: "RS-475HB",
    torqueKgCm: { v6: 10.5, v7_4: 13.0 },
    speedS60: { v6: 0.17, v7_4: 0.14 },
    voltageRange: [5.0, 8.4],
    currentMa: { idle: 5, stall: 2200 },
    weightG: 57,
    dimensionsMm: { l: 40.7, w: 20.1, h: 37.8 },
    shaftOffsetMm: 10.0,
    pinionDiamMm: 6.0,
    pulseUs: { min: 500, center: 1500, max: 2500 },
    deadbandUs: 4,
    gearType: "metal",
    bearing: "dual-ball",
    connector: "JR",
    notes: "Servo haute performance pour hexapodes",
  },
  {
    id: "mg996r",
    brand: "Tower Pro",
    model: "MG996R",
    torqueKgCm: { v6: 9.4, v7_4: 11.0 },
    speedS60: { v6: 0.2, v7_4: 0.17 },
    voltageRange: [4.8, 7.2],
    currentMa: { idle: 10, stall: 2500 },
    weightG: 55,
    dimensionsMm: { l: 40.7, w: 19.7, h: 42.9 },
    shaftOffsetMm: 10.0,
    pinionDiamMm: 6.0,
    pulseUs: { min: 500, center: 1500, max: 2500 },
    deadbandUs: 5,
    gearType: "metal",
    bearing: "plain",
    connector: "JR",
    notes: "Servo économique très répandu en robotique",
  },
  {
    id: "ds3225",
    brand: "DSServo",
    model: "DS3225",
    torqueKgCm: { v6: 22.0, v7_4: 25.5 },
    speedS60: { v6: 0.18, v7_4: 0.15 },
    voltageRange: [4.8, 8.4],
    currentMa: { idle: 8, stall: 2800 },
    weightG: 65,
    dimensionsMm: { l: 40.6, w: 20.2, h: 38.0 },
    shaftOffsetMm: 10.0,
    pinionDiamMm: 6.0,
    pulseUs: { min: 500, center: 1500, max: 2500 },
    deadbandUs: 4,
    gearType: "metal",
    bearing: "dual-ball",
    connector: "JR",
    notes: "Servo métal haute performance, résistant à l'eau",
  },
  {
    id: "hs-485hb",
    brand: "Hitec",
    model: "HS-485HB",
    torqueKgCm: { v6: 4.8 },
    speedS60: { v6: 0.22 },
    voltageRange: [4.8, 6.0],
    currentMa: { idle: 8, stall: 800 },
    weightG: 43.9,
    dimensionsMm: { l: 40.4, w: 19.8, h: 36.5 },
    shaftOffsetMm: 10.0,
    pinionDiamMm: 6.0,
    pulseUs: { min: 900, center: 1500, max: 2100 },
    deadbandUs: 8,
    gearType: "plastic",
    bearing: "ball",
    connector: "Hitec",
    notes: "Servo de référence Hitec, précis et fiable",
  },
  {
    id: "sh-0257mg",
    brand: "Savöx",
    model: "SH-0257MG",
    torqueKgCm: { v6: 2.5 },
    speedS60: { v6: 0.09 },
    voltageRange: [4.8, 6.0],
    currentMa: { idle: 5, stall: 500 },
    weightG: 11.5,
    dimensionsMm: { l: 22.8, w: 12.0, h: 24.0 },
    shaftOffsetMm: 5.5,
    pinionDiamMm: 4.8,
    pulseUs: { min: 900, center: 1500, max: 2100 },
    deadbandUs: 3,
    gearType: "metal",
    bearing: "ball",
    connector: "JR",
    notes: "Micro servo métal très précis",
  },
];

// ── Cartes servo (contrôleurs) ───────────────────────────────────────────────
const SERVO_CONTROLLERS_SEED = [
  {
    id: "lynxmotion-ssc-32u",
    brand: "Lynxmotion",
    model: "SSC-32U",
    channels: 32,
    interfaces: ["USB", "UART"],
    voltageInputV: [6.0, 9.0],
    voltageServoV: [4.8, 6.0],
    pulseUs: { min: 500, max: 2500 },
    resolutionUs: 1,
    weightG: 20,
    dimensionsMm: { l: 58, w: 40, h: 12 },
    notes: "Contrôleur série 32 canaux USB/UART. Résolution 1 µs, commandes ASCII. Référence BotBoarduino-compatible.",
  },
  {
    id: "pololu-maestro-6",
    brand: "Pololu",
    model: "Mini Maestro 6",
    channels: 6,
    interfaces: ["USB", "UART", "TTL"],
    voltageInputV: [5.0, 16.0],
    pulseUs: { min: 64, max: 3280 },
    resolutionUs: 0.25,
    weightG: 4,
    dimensionsMm: { l: 31, w: 25, h: 8 },
    notes: "6 canaux, résolution 0,25 µs, logiciel de configuration Pololu Maestro.",
  },
  {
    id: "pololu-maestro-12",
    brand: "Pololu",
    model: "Mini Maestro 12",
    channels: 12,
    interfaces: ["USB", "UART", "TTL"],
    voltageInputV: [5.0, 16.0],
    pulseUs: { min: 64, max: 3280 },
    resolutionUs: 0.25,
    weightG: 5,
    dimensionsMm: { l: 50, w: 25, h: 8 },
    notes: "12 canaux, résolution 0,25 µs.",
  },
  {
    id: "pololu-maestro-18",
    brand: "Pololu",
    model: "Mini Maestro 18",
    channels: 18,
    interfaces: ["USB", "UART", "TTL"],
    voltageInputV: [5.0, 16.0],
    pulseUs: { min: 64, max: 3280 },
    resolutionUs: 0.25,
    weightG: 7,
    dimensionsMm: { l: 62, w: 25, h: 8 },
    notes: "18 canaux — idéal hexapode 6×3 DOF.",
  },
  {
    id: "pololu-maestro-24",
    brand: "Pololu",
    model: "Mini Maestro 24",
    channels: 24,
    interfaces: ["USB", "UART", "TTL"],
    voltageInputV: [5.0, 16.0],
    pulseUs: { min: 64, max: 3280 },
    resolutionUs: 0.25,
    weightG: 9,
    dimensionsMm: { l: 79, w: 25, h: 8 },
    notes: "24 canaux.",
  },
  {
    id: "adafruit-pca9685",
    brand: "Adafruit",
    model: "PCA9685",
    channels: 16,
    interfaces: ["I2C"],
    voltageInputV: [3.0, 5.5],
    voltageServoV: [4.8, 6.0],
    pulseUs: { min: 500, max: 2500 },
    resolutionUs: 4,
    weightG: 10,
    dimensionsMm: { l: 62, w: 25, h: 10 },
    notes: "16 canaux PWM I2C. Résolution 12 bits. Plusieurs cartes chainables.",
  },
  {
    id: "robotis-usb2dynamixel",
    brand: "Robotis",
    model: "USB2Dynamixel",
    channels: 254,
    interfaces: ["USB", "Dynamixel TTL", "Dynamixel RS-485"],
    voltageInputV: [5.0, 5.0],
    pulseUs: { min: 0, max: 0 },
    resolutionUs: 0,
    weightG: 15,
    dimensionsMm: { l: 66, w: 18, h: 14 },
    notes: "Adaptateur USB pour bus Dynamixel (TTL et RS-485). Non compatible servo PWM standard.",
  },
  {
    id: "sequencer-esp32-i2c-pca9685",
    brand: "Générique",
    model: "ESP32 + PCA9685",
    channels: 32,
    interfaces: ["WiFi", "BLE", "I2C", "UART"],
    voltageInputV: [3.3, 5.0],
    voltageServoV: [4.8, 7.4],
    pulseUs: { min: 500, max: 2500 },
    resolutionUs: 4,
    weightG: 18,
    dimensionsMm: { l: 80, w: 40, h: 15 },
    notes: "Combo ESP32 + 2× PCA9685 en cascade. Solution DIY courante pour hexapodes WiFi.",
  },
];

// ── Cartes de commande ───────────────────────────────────────────────────────
const COMMAND_ELECTRONICS_SEED = [
  {
    id: "arduino-uno-r3",
    brand: "Arduino",
    model: "Uno R3",
    type: "microcontroller",
    cpu: "ATmega328P @ 16 MHz",
    flashKb: 32,
    ramKb: 2,
    gpio: 20,
    interfaces: ["UART", "I2C", "SPI", "USB"],
    voltageV: 5.0,
    currentMa: { idle: 46, active: 200 },
    weightG: 25,
    dimensionsMm: { l: 68, w: 53, h: 14 },
    notes: "Carte de référence Arduino. UART pour connexion SSC-32U ou Maestro.",
  },
  {
    id: "arduino-mega-2560",
    brand: "Arduino",
    model: "Mega 2560",
    type: "microcontroller",
    cpu: "ATmega2560 @ 16 MHz",
    flashKb: 256,
    ramKb: 8,
    gpio: 54,
    interfaces: ["UART ×4", "I2C", "SPI", "USB"],
    voltageV: 5.0,
    currentMa: { idle: 93, active: 500 },
    weightG: 37,
    dimensionsMm: { l: 101, w: 53, h: 14 },
    notes: "54 GPIO, 4 UART. Idéal pour piloter plusieurs contrôleurs SSC-32U en parallèle.",
  },
  {
    id: "arduino-nano",
    brand: "Arduino",
    model: "Nano",
    type: "microcontroller",
    cpu: "ATmega328P @ 16 MHz",
    flashKb: 32,
    ramKb: 2,
    gpio: 22,
    interfaces: ["UART", "I2C", "SPI", "USB Mini-B"],
    voltageV: 5.0,
    currentMa: { idle: 19, active: 200 },
    weightG: 7,
    dimensionsMm: { l: 45, w: 18, h: 12 },
    notes: "Format mini breadboard. Même CPU que l'Uno.",
  },
  {
    id: "arduino-nano-33-ble",
    brand: "Arduino",
    model: "Nano 33 BLE Sense",
    type: "microcontroller",
    cpu: "nRF52840 @ 64 MHz",
    flashKb: 1024,
    ramKb: 256,
    gpio: 22,
    interfaces: ["UART", "I2C", "SPI", "USB", "BLE 5.0"],
    voltageV: 3.3,
    currentMa: { idle: 8, active: 150 },
    weightG: 5,
    dimensionsMm: { l: 45, w: 18, h: 10 },
    notes: "BLE 5.0 intégré, IMU 9 axes. 3,3V logique.",
  },
  {
    id: "esp32-devkit-v1",
    brand: "Espressif",
    model: "ESP32 DevKit V1",
    type: "microcontroller",
    cpu: "ESP32 dual-core Xtensa LX6 @ 240 MHz",
    flashKb: 4096,
    ramKb: 520,
    gpio: 34,
    interfaces: ["WiFi 802.11n", "BLE 4.2", "UART ×3", "I2C ×2", "SPI ×4", "USB"],
    voltageV: 3.3,
    currentMa: { idle: 20, active: 240 },
    weightG: 10,
    dimensionsMm: { l: 51, w: 28, h: 11 },
    notes: "WiFi + BLE intégrés. Très populaire pour robots sans-fil. 3,3V logique.",
  },
  {
    id: "esp32-s3-devkit",
    brand: "Espressif",
    model: "ESP32-S3 DevKit",
    type: "microcontroller",
    cpu: "ESP32-S3 dual-core Xtensa LX7 @ 240 MHz",
    flashKb: 8192,
    ramKb: 512,
    gpio: 45,
    interfaces: ["WiFi 802.11n", "BLE 5.0", "UART ×3", "I2C ×2", "SPI ×4", "USB-OTG"],
    voltageV: 3.3,
    currentMa: { idle: 20, active: 350 },
    weightG: 12,
    dimensionsMm: { l: 68, w: 28, h: 12 },
    notes: "S3 : USB natif, plus de GPIO, AI accéléré.",
  },
  {
    id: "esp32-s3-devkitc1-n16r8",
    brand: "Espressif",
    model: "ESP32-S3-DevKitC-1 N16R8",
    type: "microcontroller",
    cpu: "ESP32-S3 dual-core Xtensa LX7 @ 240 MHz",
    flashKb: 16384,
    ramKb: 512,
    gpio: 45,
    interfaces: ["WiFi 802.11n", "BLE 5.0", "UART ×3", "I2C ×2", "SPI ×4", "USB-OTG"],
    voltageV: 3.3,
    currentMa: { idle: 30, active: 500 },
    weightG: 9,
    dimensionsMm: { l: 69, w: 26, h: 13 },
    notes: "Module ESP32-S3-WROOM-1 N16R8 : 16 Mo flash + 8 Mo PSRAM. WiFi + BLE 5.0, USB natif (2 ports USB-C). Idéal hexapode sans-fil.",
  },
  {
    id: "esp8266-nodemcu",
    brand: "Espressif",
    model: "ESP8266 NodeMCU v3",
    type: "microcontroller",
    cpu: "Tensilica L106 @ 80 MHz",
    flashKb: 4096,
    ramKb: 80,
    gpio: 11,
    interfaces: ["WiFi 802.11b/g/n", "UART", "I2C", "SPI", "USB"],
    voltageV: 3.3,
    currentMa: { idle: 15, active: 170 },
    weightG: 7,
    dimensionsMm: { l: 58, w: 31, h: 10 },
    notes: "WiFi uniquement. GPIO limités — convient pour commande simple.",
  },
  {
    id: "raspberry-pi-zero-2w",
    brand: "Raspberry Pi",
    model: "Pi Zero 2 W",
    type: "sbc",
    cpu: "ARM Cortex-A53 quad-core @ 1 GHz",
    ramKb: 512 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11n", "BLE 4.2", "UART", "I2C", "SPI", "USB Micro"],
    voltageV: 5.0,
    currentMa: { idle: 100, active: 350 },
    weightG: 10,
    dimensionsMm: { l: 65, w: 30, h: 5 },
    notes: "SBC compact. Linux complet, Python/ROS. Idéal embarqué si poids critique.",
  },
  {
    id: "raspberry-pi-3b-plus",
    brand: "Raspberry Pi",
    model: "Pi 3 B+",
    type: "sbc",
    cpu: "ARM Cortex-A53 quad-core @ 1,4 GHz",
    ramKb: 1024 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11ac", "BLE 4.2", "Ethernet", "UART", "I2C", "SPI", "USB ×4"],
    voltageV: 5.0,
    currentMa: { idle: 400, active: 1200 },
    weightG: 45,
    dimensionsMm: { l: 85, w: 56, h: 17 },
    notes: "SBC complet. Bon choix si puissance de calcul nécessaire (vision, IA embarquée).",
  },
  {
    id: "raspberry-pi-4b-2g",
    brand: "Raspberry Pi",
    model: "Pi 4 B (2 Go)",
    type: "sbc",
    cpu: "ARM Cortex-A72 quad-core @ 1,8 GHz",
    ramKb: 2048 * 1024,
    gpio: 40,
    interfaces: ["WiFi 802.11ac", "BLE 5.0", "Ethernet Gbit", "UART", "I2C", "SPI", "USB 3.0 ×2", "USB 2.0 ×2"],
    voltageV: 5.0,
    currentMa: { idle: 600, active: 3000 },
    weightG: 46,
    dimensionsMm: { l: 85, w: 56, h: 17 },
    notes: "SBC haute performance. Consommation élevée — batterie LiPo nécessaire.",
  },
  {
    id: "teensy-40",
    brand: "PJRC",
    model: "Teensy 4.0",
    type: "microcontroller",
    cpu: "ARM Cortex-M7 @ 600 MHz",
    flashKb: 1984,
    ramKb: 1024,
    gpio: 40,
    interfaces: ["UART ×8", "I2C ×3", "SPI ×3", "USB", "CAN"],
    voltageV: 3.3,
    currentMa: { idle: 10, active: 100 },
    weightG: 7,
    dimensionsMm: { l: 35, w: 18, h: 5 },
    notes: "MCU très rapide. Excellent pour calcul cinématique temps réel (Hexapod).",
  },
  {
    id: "teensy-41",
    brand: "PJRC",
    model: "Teensy 4.1",
    type: "microcontroller",
    cpu: "ARM Cortex-M7 @ 600 MHz",
    flashKb: 7936,
    ramKb: 1024,
    gpio: 55,
    interfaces: ["UART ×8", "I2C ×3", "SPI ×3", "USB", "CAN ×2", "Ethernet"],
    voltageV: 3.3,
    currentMa: { idle: 10, active: 120 },
    weightG: 9,
    dimensionsMm: { l: 61, w: 18, h: 5 },
    notes: "Version étendue du 4.0 avec Ethernet et plus de GPIO.",
  },
  {
    id: "stm32-nucleo-f446re",
    brand: "STMicroelectronics",
    model: "Nucleo-F446RE",
    type: "microcontroller",
    cpu: "ARM Cortex-M4 @ 180 MHz",
    flashKb: 512,
    ramKb: 128,
    gpio: 76,
    interfaces: ["UART ×6", "I2C ×3", "SPI ×4", "USB", "CAN"],
    voltageV: 3.3,
    currentMa: { idle: 15, active: 300 },
    weightG: 28,
    dimensionsMm: { l: 69, w: 51, h: 14 },
    notes: "MCU STM32 haute perf. Compatible Arduino Uno shield via connecteur.",
  },
];

// ── Capteurs / périphériques ─────────────────────────────────────────────────
export const PERIPHERAL_CATEGORIES_SEED: Record<string, { label: string; icon: string }> = {
  imu: { label: "Inclinaison / IMU", icon: "🧭" },
  distance: { label: "Distance", icon: "📡" },
  led: { label: "LED", icon: "💡" },
  button: { label: "Bouton", icon: "🔘" },
  voltage: { label: "Tension / courant", icon: "🔋" },
  display: { label: "Écran", icon: "🖥️" },
  audio: { label: "Son", icon: "🔊" },
  other: { label: "Autre", icon: "🧩" },
};

const PERIPHERALS_SEED = [
  { id: "mpu6050", category: "imu", name: "MPU6050", description: "Accéléromètre + gyroscope 6 axes (inclinaison)", interfaces: ["I2C"], icon: "🧭" },
  { id: "mpu9250", category: "imu", name: "MPU9250", description: "IMU 9 axes (accéléro + gyro + magnéto)", interfaces: ["I2C", "SPI"], icon: "🧭" },
  { id: "bno055", category: "imu", name: "BNO055", description: "IMU 9 axes avec fusion intégrée (orientation absolue)", interfaces: ["I2C"], icon: "🧭" },
  { id: "icm20948", category: "imu", name: "ICM-20948", description: "IMU 9 axes basse conso", interfaces: ["I2C", "SPI"], icon: "🧭" },
  { id: "adxl345", category: "imu", name: "ADXL345", description: "Accéléromètre 3 axes", interfaces: ["I2C", "SPI"], icon: "📐" },
  { id: "hc-sr04", category: "distance", name: "HC-SR04", description: "Télémètre ultrason (2–400 cm)", interfaces: ["GPIO"], icon: "📡" },
  { id: "us-100", category: "distance", name: "US-100", description: "Télémètre ultrason (UART/GPIO, compensé température)", interfaces: ["UART", "GPIO"], icon: "📡" },
  { id: "vl53l0x", category: "distance", name: "VL53L0X", description: "Télémètre laser ToF (jusqu'à ~2 m)", interfaces: ["I2C"], icon: "📡" },
  { id: "gp2y0a21", category: "distance", name: "Sharp GP2Y0A21", description: "Capteur de distance IR analogique (10–80 cm)", interfaces: ["Analog"], icon: "📡" },
  { id: "ir-obstacle", category: "distance", name: "Capteur IR obstacle", description: "Détecteur d'obstacle infrarouge tout-ou-rien", interfaces: ["GPIO"], icon: "📡" },
  { id: "led", category: "led", name: "LED", description: "LED simple", interfaces: ["GPIO"], icon: "💡" },
  { id: "led-rgb", category: "led", name: "LED RGB", description: "LED RGB (3 canaux PWM)", interfaces: ["PWM"], icon: "🌈" },
  { id: "ws2812", category: "led", name: "NeoPixel WS2812", description: "Bandeau / anneau de LEDs adressables", interfaces: ["GPIO"], icon: "▦" },
  { id: "btn-red", category: "button", name: "Bouton poussoir rouge", description: "Bouton poussoir momentané (rouge)", interfaces: ["GPIO"], icon: "🔴" },
  { id: "btn-green", category: "button", name: "Bouton poussoir vert", description: "Bouton poussoir momentané (vert)", interfaces: ["GPIO"], icon: "🟢" },
  { id: "btn-blue", category: "button", name: "Bouton poussoir bleu", description: "Bouton poussoir momentané (bleu)", interfaces: ["GPIO"], icon: "🔵" },
  { id: "btn-yellow", category: "button", name: "Bouton poussoir jaune", description: "Bouton poussoir momentané (jaune)", interfaces: ["GPIO"], icon: "🟡" },
  { id: "voltage-divider", category: "voltage", name: "Détecteur de tension", description: "Module diviseur de tension (0–25 V)", interfaces: ["Analog"], icon: "🔋" },
  { id: "ina219", category: "voltage", name: "INA219", description: "Mesure tension + courant (I2C)", interfaces: ["I2C"], icon: "🔋" },
  { id: "ina226", category: "voltage", name: "INA226", description: "Mesure tension + courant haute précision (I2C)", interfaces: ["I2C"], icon: "🔋" },
  { id: "ssd1306", category: "display", name: "OLED SSD1306", description: "Écran OLED 128×64 I2C", interfaces: ["I2C"], icon: "🖥️" },
  { id: "buzzer", category: "audio", name: "Buzzer", description: "Buzzer piézo (signal sonore)", interfaces: ["GPIO"], icon: "🔊" },
];

export interface SeedEntry {
  id: string;
  data: Record<string, unknown>;
}

/** Catalogues seed, indexés par `kind`, dans l'ordre d'affichage. */
export const CATALOG_SEED: Record<CatalogKind, SeedEntry[]> = {
  servoType: SERVO_TYPES_SEED.map((d) => ({ id: d.id, data: d as Record<string, unknown> })),
  servoController: SERVO_CONTROLLERS_SEED.map((d) => ({ id: d.id, data: d as Record<string, unknown> })),
  commandElectronics: COMMAND_ELECTRONICS_SEED.map((d) => ({ id: d.id, data: d as Record<string, unknown> })),
  peripheral: PERIPHERALS_SEED.map((d) => ({ id: d.id, data: d as Record<string, unknown> })),
};
